# Generated by Django 4.1.7 on 2023-04-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0002_alter_membership_team_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='second_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_team', to='web_site.team', verbose_name='second team'),
        ),
    ]
