# Generated by Django 4.1.7 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0003_alter_challenge_second_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'active'), ('waiting_result', 'waiting_result'), ('dispute', 'dispute'), ('finished', 'finished')], default='active', max_length=20, null=True, verbose_name='Challenge status'),
        ),
    ]
