# Generated by Django 4.1.7 on 2023-04-13 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0005_alter_challenge_modified_alter_challenge_time_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Map_name')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='first_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_map', to='web_site.maps', verbose_name='first_map'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='second_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_map', to='web_site.maps', verbose_name='second_map'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='third_map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_map', to='web_site.maps', verbose_name='third_map'),
        ),
    ]
