# Generated by Django 4.1.7 on 2023-04-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0006_maps_challenge_first_map_challenge_second_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(blank=True, default=1000, null=True),
        ),
    ]
