# Generated by Django 4.1.7 on 2023-04-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_site', '0009_team_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
