# Generated by Django 4.1.7 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ip_address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
