# Generated by Django 4.1.7 on 2023-04-13 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
    ]
